using AutoMapper;
using GeekShopping.ProductAPI.Data.DTOs;
using GeekShopping.ProductAPI.Model;
using Microsoft.Extensions.Logging.Abstractions;

namespace GeekShopping.ProductAPI.Configs.Mappings
{
    /// <summary>
    /// Represents the configuration required for setting up <see cref="AutoMapper"/> mappings between application-specific data transfer objects and entities.
    /// </summary>
    /// <remarks>
    /// This class is responsible for defining the mapping logic between <c>ProductDto</c> and <c>Product</c> objects and vice versa.
    /// It leverages the <c>AutoMapper</c> library to create a centralized mapping configuration for the application.
    /// </remarks>
    /// <example>
    /// The mapping configuration generated by this class can be used for handling object transformations efficiently, especially in scenarios
    /// where complex domain models need to interact with simplified view models or DTOs.
    /// </example>
    public static class MappingConfiguration
    {
        /// <summary>
        /// Configures and registers mappings between data transfer objects (DTOs) and entities using AutoMapper.
        /// </summary>
        /// <remarks>
        /// This method defines bidirectional mappings between <c>ProductDto</c> and <c>Product</c>, enabling seamless transformations.
        /// It leverages AutoMapper to centralize and streamline the mapping logic for the application.
        /// </remarks>
        /// <returns>
        /// A <see cref="AutoMapper.MapperConfiguration"/> instance that encapsulates the defined mapping configurations.
        /// </returns>
        public static MapperConfiguration RegisterMappings()
        {
            MapperConfiguration mappingConfiguration = new((config) =>
                {
                    config.CreateMap<Product, ProductDto>()
                        .ForMember(
                            (destination) => destination.Version,
                            (options) => options.MapFrom((src) => src.Version)
                        )
                        .ReverseMap();
                },
                new NullLoggerFactory()
            );

            return mappingConfiguration;
        }
    }
}